---
- name: Export inventory source from AAP (AWX/Tower)
  hosts: localhost
  gather_facts: false
  vars:
    validate_certs: false


  tasks:
    - name: Get inventory source info
      ansible.controller.export:
        controller_host: "{{ AAP_HOSTNAME }}"
        controller_username: "{{ AAP_USERNAME }}"
        controller_password: "{{ AAP_PASSWORD }}"
        inventory_sources: ["gci"]
        validate_certs: "{{ validate_certs }}"